import { defineConfig } from 'vitest/config';
import path from 'path';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/__tests__/setup.ts'],
    include: [
      'src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
      'src/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
    ],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/cypress/**',
      '**/.{idea,git,cache,output,temp}/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: [
        'src/**/*.{js,jsx,ts,tsx}',
        '!src/**/*.d.ts',
        '!src/**/*.test.{js,jsx,ts,tsx}',
        '!src/**/*.spec.{js,jsx,ts,tsx}',
        '!src/__tests__/**',
        '!src/**/index.{js,ts}',
      ],
      exclude: [
        'coverage/**',
        'dist/**',
        '**/[.]**',
        'packages/*/test?(s)/**',
        '**/*.d.ts',
        '**/virtual:*',
        '**/__x00__*',
        '**/\x00*',
        'cypress/**',
        'test?(s)/**',
        'test?(-*).?(c|m)[jt]s?(x)',
        '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
        '**/__tests__/**',
        '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
        '**/vitest.{workspace,projects}.[jt]s?(on)',
        '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 70,
        statements: 80,
      },
      watermarks: {
        statements: [70, 85],
        functions: [70, 85],
        branches: [60, 80],
        lines: [70, 85],
      },
    },
    benchmark: {
      include: ['src/**/*.{bench,benchmark}.{js,ts}'],
      exclude: ['node_modules', 'dist'],
    },
    testTimeout: 30000,
    hookTimeout: 30000,
    teardownTimeout: 30000,
    maxConcurrency: 10,
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: false,
        maxThreads: 4,
        minThreads: 1,
      },
    },
    reporters: ['default', 'html'],
    outputFile: {
      html: './coverage/test-results.html',
      json: './coverage/test-results.json',
      junit: './coverage/junit.xml',
    },
    watch: false,
    ui: false,
    open: false,
    api: {
      port: 51204,
      host: 'localhost',
    },
    logHeapUsage: true,
    silent: false,
    isolate: true,
    shuffle: {
      files: true,
      tests: true,
      seed: Date.now(),
    },
    retry: 2,
    diff: {
      outputTruncateLength: 80,
      outputDiffLines: 15,
    },
    chaiConfig: {
      truncateThreshold: 40,
      includeStack: true,
      showDiff: true,
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@@': path.resolve(__dirname, './'),
      '@components': path.resolve(__dirname, './src/components'),
      '@hooks': path.resolve(__dirname, './src/hooks'),
      '@services': path.resolve(__dirname, './src/services'),
      '@utils': path.resolve(__dirname, './src/utils'),
      '@types': path.resolve(__dirname, './src/types'),
      '@assets': path.resolve(__dirname, './src/assets'),
      '@pages': path.resolve(__dirname, './src/pages'),
      '@store': path.resolve(__dirname, './src/store'),
      '@api': path.resolve(__dirname, './api'),
      '@shared': path.resolve(__dirname, './shared'),
      '@supabase': path.resolve(__dirname, './supabase'),
      '@migrations': path.resolve(__dirname, './supabase/migrations'),
    },
  },
  esbuild: {
    target: 'es2020',
    format: 'esm',
    platform: 'browser',
    jsx: 'automatic',
    jsxImportSource: 'react',
    jsxDev: false,
    minify: false,
    sourcemap: true,
    sourcesContent: true,
  },
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'react-router-dom',
      '@tanstack/react-query',
      'framer-motion',
      'lucide-react',
      'sonner',
      'recharts',
      'three',
      'zustand',
    ],
    exclude: ['@testing-library/react', '@testing-library/jest-dom'],
  },
  server: {
    port: 3001,
    host: 'localhost',
    open: false,
    cors: true,
    hmr: {
      port: 3002,
    },
  },
  preview: {
    port: 3003,
    host: 'localhost',
    open: false,
  },
  build: {
    target: 'es2020',
    outDir: 'dist',
    assetsDir: 'assets',
    sourcemap: true,
    minify: 'esbuild',
    cssCodeSplit: true,
    rollupOptions: {
      output: {
        manualChunks: {
          'react-vendor': ['react', 'react-dom', 'react-router-dom'],
          'query-vendor': ['@tanstack/react-query'],
          'animation-vendor': ['framer-motion'],
          'ui-vendor': ['lucide-react', 'sonner'],
          'chart-vendor': ['recharts'],
          '3d-vendor': ['three'],
          'state-vendor': ['zustand'],
        },
      },
    },
  },
  css: {
    devSourcemap: true,
    postcss: {
      plugins: [
        require('tailwindcss'),
        require('autoprefixer'),
      ],
    },
  },
  define: {
    __DEV__: JSON.stringify(true),
    __TEST__: JSON.stringify(true),
    __PROD__: JSON.stringify(false),
    __VERSION__: JSON.stringify('1.0.0'),
    __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
  },
  envPrefix: ['VITE_', 'REACT_APP_'],
  envDir: './',
  logLevel: 'info',
  clearScreen: false,
  mode: 'test',
});