import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import SEODashboard from '../dashboard';
import { seoService } from '@/services/seo';

// Mock the SEO service
vi.mock('@/services/seo', () => ({
  seoService: {
    getSettings: vi.fn(),
    getKeywords: vi.fn(),
    getSitemaps: vi.fn(),
    getMetaTags: vi.fn(),
    getLinks: vi.fn(),
    getAnalysis: vi.fn(),
    getCompetitors: vi.fn(),
    getRankings: vi.fn(),
    getReports: vi.fn()
  }
}));

// Mock toast
vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn()
  }
}));

const createWrapper = () => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false }
    }
  });
  
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
};

describe('SEODashboard', () => {
  const mockSettings = {
    id: '1',
    siteName: 'Test Site',
    siteDescription: 'Test Description',
    siteUrl: 'https://example.com',
    language: 'zh-CN',
    charset: 'UTF-8',
    robotsTxt: 'User-agent: *\nDisallow: /admin/',
    googleAnalyticsId: 'UA-123456789-1',
    baiduAnalyticsId: 'baidu-123',
    defaultMetaTitle: 'Default Title',
    defaultMetaDescription: 'Default Description',
    defaultMetaKeywords: ['test', 'seo'],
    socialMedia: {},
    hreflang: [],
    crawlDelay: 1,
    sitemapAutoSubmit: true,
    lastUpdated: new Date().toISOString()
  };

  const mockKeywords = [
    {
      id: '1',
      keyword: 'test keyword',
      searchVolume: 1000,
      competition: 'medium',
      difficulty: 45,
      cpc: 2.5,
      category: 'technology',
      tags: ['test', 'seo'],
      trends: [100, 120, 110, 130],
      relatedKeywords: ['related1', 'related2'],
      isTracked: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  const mockSitemaps = [
    {
      id: '1',
      name: 'Main Sitemap',
      url: '/sitemap.xml',
      type: 'xml',
      pages: 150,
      size: 25600,
      lastModified: new Date().toISOString(),
      isAutoGenerated: true,
      submissionStatus: {
        google: 'submitted',
        baidu: 'pending',
        bing: 'submitted'
      }
    }
  ];

  const mockMetaTags = [
    {
      id: '1',
      pageUrl: '/',
      title: 'Home Page',
      description: 'Welcome to our website',
      keywords: ['home', 'welcome'],
      ogTitle: 'Home - Our Website',
      ogDescription: 'Welcome to our amazing website',
      ogImage: 'https://example.com/og-image.jpg',
      ogType: 'website',
      twitterCard: 'summary_large_image',
      twitterTitle: 'Home - Our Website',
      twitterDescription: 'Welcome to our amazing website',
      twitterImage: 'https://example.com/twitter-image.jpg',
      canonicalUrl: 'https://example.com/',
      robotsContent: 'index,follow',
      hreflang: [],
      customTags: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  const mockLinks = [
    {
      id: '1',
      url: 'https://example.com/page1',
      anchorText: 'Page 1',
      type: 'internal',
      status: 'active',
      nofollow: false,
      target: '_self',
      clicks: 100,
      lastChecked: new Date().toISOString(),
      isBroken: false,
      redirectType: null,
      redirectUrl: null,
      pageUrl: '/',
      position: 1
    }
  ];

  const mockAnalysis = {
    id: '1',
    url: 'https://example.com/test-page',
    overallScore: 85,
    pageSpeedScore: 90,
    mobileScore: 88,
    accessibilityScore: 92,
    seoScore: 85,
    issues: [],
    recommendations: [],
    keywords: {
      primary: 'test keyword',
      secondary: ['related1', 'related2'],
      density: 2.5
    },
    contentLength: 1500,
    readingLevel: 'intermediate',
    createdAt: new Date().toISOString()
  };

  const mockCompetitors = [
    {
      id: '1',
      domain: 'competitor1.com',
      name: 'Competitor 1',
      keywords: ['keyword1', 'keyword2'],
      commonKeywords: ['shared1'],
      ranking: 2,
      backlinks: 500,
      domainAuthority: 65,
      pageSpeed: 85,
      lastAnalyzed: new Date().toISOString(),
      strengths: ['content', 'backlinks'],
      weaknesses: ['speed', 'mobile'],
      opportunities: ['keywords', 'content'],
      threats: ['rankings', 'traffic']
    }
  ];

  const mockRankings = [
    {
      id: '1',
      keyword: 'test keyword',
      currentRank: 5,
      previousRank: 8,
      rankChange: 3,
      searchVolume: 1000,
      cpc: 2.5,
      competition: 65,
      url: 'https://example.com/test-page',
      engine: 'google',
      location: 'US',
      category: 'technology',
      tags: ['test', 'seo'],
      lastUpdated: new Date().toISOString(),
      trendData: []
    }
  ];

  const mockReports = [
    {
      id: '1',
      name: 'Monthly SEO Report',
      type: 'monthly',
      frequency: 'monthly',
      recipients: ['admin@example.com'],
      metrics: ['rankings', 'traffic', 'keywords'],
      description: 'Monthly SEO performance report',
      enabled: true,
      lastGenerated: new Date().toISOString(),
      nextScheduled: new Date().toISOString(),
      status: 'active',
      template: 'default',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  beforeEach(() => {
    vi.clearAllMocks();
    
    // Setup default mocks
    vi.mocked(seoService.getSettings).mockResolvedValue(mockSettings);
    vi.mocked(seoService.getKeywords).mockResolvedValue(mockKeywords);
    vi.mocked(seoService.getSitemaps).mockResolvedValue(mockSitemaps);
    vi.mocked(seoService.getMetaTags).mockResolvedValue(mockMetaTags);
    vi.mocked(seoService.getLinks).mockResolvedValue(mockLinks);
    vi.mocked(seoService.getAnalysis).mockResolvedValue(mockAnalysis);
    vi.mocked(seoService.getCompetitors).mockResolvedValue(mockCompetitors);
    vi.mocked(seoService.getRankings).mockResolvedValue(mockRankings);
    vi.mocked(seoService.getReports).mockResolvedValue(mockReports);
  });

  describe('Dashboard Rendering', () => {
    it('should render the dashboard with all components', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
        expect(screen.getByText('全面的搜索引擎优化管理和分析工具')).toBeInTheDocument();
      });

      // Check for tab navigation
      expect(screen.getByText('概览')).toBeInTheDocument();
      expect(screen.getByText('设置')).toBeInTheDocument();
      expect(screen.getByText('关键词')).toBeInTheDocument();
      expect(screen.getByText('排名追踪')).toBeInTheDocument();
      expect(screen.getByText('站点地图')).toBeInTheDocument();
      expect(screen.getByText('Meta标签')).toBeInTheDocument();
      expect(screen.getByText('链接优化')).toBeInTheDocument();
      expect(screen.getByText('竞争对手')).toBeInTheDocument();
      expect(screen.getByText('报告')).toBeInTheDocument();
    });

    it('should display SEO health overview', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 健康度概览')).toBeInTheDocument();
        expect(screen.getByText('85%')).toBeInTheDocument(); // Overall score
        expect(screen.getByText('SEO 总评分')).toBeInTheDocument();
      });

      // Check for key metrics
      expect(screen.getByText('1')).toBeInTheDocument(); // Keywords count
      expect(screen.getByText('关键词数量')).toBeInTheDocument();
      expect(screen.getByText('1')).toBeInTheDocument(); // Sitemaps count
      expect(screen.getByText('站点地图')).toBeInTheDocument();
      expect(screen.getByText('1')).toBeInTheDocument(); // Competitors count
      expect(screen.getByText('竞争对手')).toBeInTheDocument();
    });

    it('should display keyword status card', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('关键词状态')).toBeInTheDocument();
      });

      expect(screen.getByText('总关键词')).toBeInTheDocument();
      expect(screen.getByText('高竞争度')).toBeInTheDocument();
      expect(screen.getByText('长尾关键词')).toBeInTheDocument();
    });

    it('should display sitemap status card', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('站点地图状态')).toBeInTheDocument();
      });

      expect(screen.getByText('XML站点地图')).toBeInTheDocument();
      expect(screen.getByText('图片站点地图')).toBeInTheDocument();
      expect(screen.getByText('最后更新')).toBeInTheDocument();
    });

    it('should display meta tags status card', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('Meta标签状态')).toBeInTheDocument();
      });

      expect(screen.getByText('页面标签')).toBeInTheDocument();
      expect(screen.getByText('Open Graph')).toBeInTheDocument();
      expect(screen.getByText('Twitter Card')).toBeInTheDocument();
    });
  });

  describe('Tab Navigation', () => {
    it('should navigate to settings tab', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const settingsTab = screen.getByText('设置');
      fireEvent.click(settingsTab);

      await waitFor(() => {
        // Settings panel should be visible
        expect(screen.getByText('SEO设置')).toBeInTheDocument();
      });
    });

    it('should navigate to keywords tab', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const keywordsTab = screen.getByText('关键词');
      fireEvent.click(keywordsTab);

      await waitFor(() => {
        // Keywords management should be visible
        expect(screen.getByText('关键词管理')).toBeInTheDocument();
      });
    });

    it('should navigate to rankings tab', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const rankingsTab = screen.getByText('排名追踪');
      fireEvent.click(rankingsTab);

      await waitFor(() => {
        // Rankings tracker should be visible
        expect(screen.getByText('排名追踪')).toBeInTheDocument();
      });
    });

    it('should navigate to reports tab', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const reportsTab = screen.getByText('报告');
      fireEvent.click(reportsTab);

      await waitFor(() => {
        // Reports management should be visible
        expect(screen.getByText('SEO报告管理')).toBeInTheDocument();
      });
    });
  });

  describe('Action Buttons', () => {
    it('should handle refresh data button', async () => {
      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const refreshButton = screen.getByText('刷新数据');
      fireEvent.click(refreshButton);

      // Should trigger data refresh
      await waitFor(() => {
        expect(window.location.reload).toBeDefined();
      });
    });

    it('should handle export report button', async () => {
      // Mock createObjectURL and revokeObjectURL
      global.URL.createObjectURL = vi.fn().mockReturnValue('blob:mock-url');
      global.URL.revokeObjectURL = vi.fn();

      // Mock createElement for download link
      const mockLink = {
        href: '',
        download: '',
        click: vi.fn(),
        style: { display: '' }
      };
      vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any);
      vi.spyOn(document.body, 'appendChild').mockImplementation(() => {});
      vi.spyOn(document.body, 'removeChild').mockImplementation(() => {});

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      const exportButton = screen.getByText('导出报告');
      fireEvent.click(exportButton);

      await waitFor(() => {
        expect(document.createElement).toHaveBeenCalledWith('a');
        expect(mockLink.click).toHaveBeenCalled();
      });
    });
  });

  describe('Error Handling', () => {
    it('should handle API errors gracefully', async () => {
      vi.mocked(seoService.getSettings).mockRejectedValueOnce(new Error('API Error'));

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      // Dashboard should still render despite API errors
      expect(screen.getByText('刷新数据')).toBeInTheDocument();
      expect(screen.getByText('导出报告')).toBeInTheDocument();
    });

    it('should handle empty data gracefully', async () => {
      vi.mocked(seoService.getKeywords).mockResolvedValueOnce([]);
      vi.mocked(seoService.getSitemaps).mockResolvedValueOnce([]);
      vi.mocked(seoService.getMetaTags).mockResolvedValueOnce([]);
      vi.mocked(seoService.getCompetitors).mockResolvedValueOnce([]);

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();
      });

      // Should show 0 for empty data
      expect(screen.getByText('0')).toBeInTheDocument();
    });
  });

  describe('Loading States', () => {
    it('should show loading states while fetching data', async () => {
      // Mock slow API responses
      vi.mocked(seoService.getSettings).mockImplementationOnce(() => 
        new Promise(resolve => setTimeout(() => resolve(mockSettings), 100))
      );

      render(<SEODashboard />, { wrapper: createWrapper() });

      // Initially should show loading state
      expect(screen.getByText('SEO 优化中心')).toBeInTheDocument();

      await waitFor(() => {
        expect(screen.getByText('85%')).toBeInTheDocument();
      });
    });
  });

  describe('SEO Score Calculation', () => {
    it('should calculate SEO score correctly for excellent status', async () => {
      const excellentAnalysis = { ...mockAnalysis, overallScore: 90 };
      vi.mocked(seoService.getAnalysis).mockResolvedValueOnce(excellentAnalysis);

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('90%')).toBeInTheDocument();
      });
    });

    it('should calculate SEO score correctly for good status', async () => {
      const goodAnalysis = { ...mockAnalysis, overallScore: 70 };
      vi.mocked(seoService.getAnalysis).mockResolvedValueOnce(goodAnalysis);

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('70%')).toBeInTheDocument();
      });
    });

    it('should calculate SEO score correctly for needs improvement status', async () => {
      const needsImprovementAnalysis = { ...mockAnalysis, overallScore: 50 };
      vi.mocked(seoService.getAnalysis).mockResolvedValueOnce(needsImprovementAnalysis);

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('50%')).toBeInTheDocument();
      });
    });

    it('should calculate SEO score correctly for poor status', async () => {
      const poorAnalysis = { ...mockAnalysis, overallScore: 30 };
      vi.mocked(seoService.getAnalysis).mockResolvedValueOnce(poorAnalysis);

      render(<SEODashboard />, { wrapper: createWrapper() });

      await waitFor(() => {
        expect(screen.getByText('30%')).toBeInTheDocument();
      });
    });
  });
});