/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root.lazy'
import { Route as AdminGalleryImport } from './pages/admin/gallery'
import { Route as AdminEditImport } from './pages/admin/edit'
import { Route as AdminBlogImport } from './pages/admin/blog'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const AuthLoginLazyImport = createFileRoute('/auth/login')()
const AdminArticlesLazyImport = createFileRoute('/admin/articles')()
const AdminAboutLazyImport = createFileRoute('/admin/about')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/admin/index.lazy').then((d) => d.Route))

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/auth/login.lazy').then((d) => d.Route))

const AdminArticlesLazyRoute = AdminArticlesLazyImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/admin/articles.lazy').then((d) => d.Route))

const AdminAboutLazyRoute = AdminAboutLazyImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/admin/about.lazy').then((d) => d.Route))

const AdminGalleryRoute = AdminGalleryImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRoute,
} as any)

const AdminEditRoute = AdminEditImport.update({
  id: '/admin/edit',
  path: '/admin/edit',
  getParentRoute: () => rootRoute,
} as any)

const AdminBlogRoute = AdminBlogImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogImport
      parentRoute: typeof rootRoute
    }
    '/admin/edit': {
      id: '/admin/edit'
      path: '/admin/edit'
      fullPath: '/admin/edit'
      preLoaderRoute: typeof AdminEditImport
      parentRoute: typeof rootRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryImport
      parentRoute: typeof rootRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/edit': typeof AdminEditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/about': typeof AdminAboutLazyRoute
  '/admin/articles': typeof AdminArticlesLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/admin': typeof AdminIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/edit': typeof AdminEditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/about': typeof AdminAboutLazyRoute
  '/admin/articles': typeof AdminArticlesLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/admin': typeof AdminIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/edit': typeof AdminEditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/about': typeof AdminAboutLazyRoute
  '/admin/articles': typeof AdminArticlesLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/blog'
    | '/admin/edit'
    | '/admin/gallery'
    | '/admin/about'
    | '/admin/articles'
    | '/auth/login'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/blog'
    | '/admin/edit'
    | '/admin/gallery'
    | '/admin/about'
    | '/admin/articles'
    | '/auth/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/blog'
    | '/admin/edit'
    | '/admin/gallery'
    | '/admin/about'
    | '/admin/articles'
    | '/auth/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminEditRoute: typeof AdminEditRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminAboutLazyRoute: typeof AdminAboutLazyRoute
  AdminArticlesLazyRoute: typeof AdminArticlesLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminEditRoute: AdminEditRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminAboutLazyRoute: AdminAboutLazyRoute,
  AdminArticlesLazyRoute: AdminArticlesLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.lazy.tsx",
      "children": [
        "/",
        "/admin/blog",
        "/admin/edit",
        "/admin/gallery",
        "/admin/about",
        "/admin/articles",
        "/auth/login",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin/blog": {
      "filePath": "admin/blog.tsx"
    },
    "/admin/edit": {
      "filePath": "admin/edit.tsx"
    },
    "/admin/gallery": {
      "filePath": "admin/gallery.tsx"
    },
    "/admin/about": {
      "filePath": "admin/about.lazy.tsx"
    },
    "/admin/articles": {
      "filePath": "admin/articles.lazy.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
