/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root.lazy'
import { Route as IndexImport } from './pages/index'
import { Route as DashboardIndexImport } from './pages/dashboard/index'
import { Route as DashboardVisitLogImport } from './pages/dashboard/visit-log'
import { Route as DashboardUsersImport } from './pages/dashboard/users'
import { Route as DashboardThirdImport } from './pages/dashboard/third'
import { Route as DashboardTagsImport } from './pages/dashboard/tags'
import { Route as DashboardPersonalInfoImport } from './pages/dashboard/personalInfo'
import { Route as DashboardMediaImport } from './pages/dashboard/media'
import { Route as DashboardLinksImport } from './pages/dashboard/links'
import { Route as DashboardCommentsImport } from './pages/dashboard/comments'
import { Route as DashboardCategoriesImport } from './pages/dashboard/categories'
import { Route as DashboardBlogImport } from './pages/dashboard/blog'
import { Route as DashboardArticlesImport } from './pages/dashboard/articles'
import { Route as AuthForgotPasswordImport } from './pages/auth/forgot-password'

// Create Virtual Routes

const DashboardSettingsLazyImport = createFileRoute('/dashboard/settings')()
const DashboardEditorLazyImport = createFileRoute('/dashboard/editor')()
const DashboardAnalyticsLazyImport = createFileRoute('/dashboard/analytics')()
const DashboardAboutLazyImport = createFileRoute('/dashboard/about')()
const AuthLoginLazyImport = createFileRoute('/auth/login')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSettingsLazyRoute = DashboardSettingsLazyImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/dashboard/settings.lazy').then((d) => d.Route),
)

const DashboardEditorLazyRoute = DashboardEditorLazyImport.update({
  id: '/dashboard/editor',
  path: '/dashboard/editor',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/dashboard/editor.lazy').then((d) => d.Route),
)

const DashboardAnalyticsLazyRoute = DashboardAnalyticsLazyImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/dashboard/analytics.lazy').then((d) => d.Route),
)

const DashboardAboutLazyRoute = DashboardAboutLazyImport.update({
  id: '/dashboard/about',
  path: '/dashboard/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/dashboard/about.lazy').then((d) => d.Route),
)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/auth/login.lazy').then((d) => d.Route))

const DashboardVisitLogRoute = DashboardVisitLogImport.update({
  id: '/dashboard/visit-log',
  path: '/dashboard/visit-log',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRoute,
} as any)

const DashboardThirdRoute = DashboardThirdImport.update({
  id: '/dashboard/third',
  path: '/dashboard/third',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTagsRoute = DashboardTagsImport.update({
  id: '/dashboard/tags',
  path: '/dashboard/tags',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPersonalInfoRoute = DashboardPersonalInfoImport.update({
  id: '/dashboard/personalInfo',
  path: '/dashboard/personalInfo',
  getParentRoute: () => rootRoute,
} as any)

const DashboardMediaRoute = DashboardMediaImport.update({
  id: '/dashboard/media',
  path: '/dashboard/media',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLinksRoute = DashboardLinksImport.update({
  id: '/dashboard/links',
  path: '/dashboard/links',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCommentsRoute = DashboardCommentsImport.update({
  id: '/dashboard/comments',
  path: '/dashboard/comments',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCategoriesRoute = DashboardCategoriesImport.update({
  id: '/dashboard/categories',
  path: '/dashboard/categories',
  getParentRoute: () => rootRoute,
} as any)

const DashboardBlogRoute = DashboardBlogImport.update({
  id: '/dashboard/blog',
  path: '/dashboard/blog',
  getParentRoute: () => rootRoute,
} as any)

const DashboardArticlesRoute = DashboardArticlesImport.update({
  id: '/dashboard/articles',
  path: '/dashboard/articles',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/articles': {
      id: '/dashboard/articles'
      path: '/dashboard/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof DashboardArticlesImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/blog': {
      id: '/dashboard/blog'
      path: '/dashboard/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardBlogImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/comments': {
      id: '/dashboard/comments'
      path: '/dashboard/comments'
      fullPath: '/dashboard/comments'
      preLoaderRoute: typeof DashboardCommentsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/dashboard/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/dashboard/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/personalInfo': {
      id: '/dashboard/personalInfo'
      path: '/dashboard/personalInfo'
      fullPath: '/dashboard/personalInfo'
      preLoaderRoute: typeof DashboardPersonalInfoImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/tags': {
      id: '/dashboard/tags'
      path: '/dashboard/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/third': {
      id: '/dashboard/third'
      path: '/dashboard/third'
      fullPath: '/dashboard/third'
      preLoaderRoute: typeof DashboardThirdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/visit-log': {
      id: '/dashboard/visit-log'
      path: '/dashboard/visit-log'
      fullPath: '/dashboard/visit-log'
      preLoaderRoute: typeof DashboardVisitLogImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/dashboard/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/editor': {
      id: '/dashboard/editor'
      path: '/dashboard/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof DashboardEditorLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/personalInfo': typeof DashboardPersonalInfoRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard/third': typeof DashboardThirdRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/visit-log': typeof DashboardVisitLogRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/dashboard/about': typeof DashboardAboutLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/editor': typeof DashboardEditorLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/personalInfo': typeof DashboardPersonalInfoRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard/third': typeof DashboardThirdRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/visit-log': typeof DashboardVisitLogRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/dashboard/about': typeof DashboardAboutLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/editor': typeof DashboardEditorLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/blog': typeof DashboardBlogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/personalInfo': typeof DashboardPersonalInfoRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard/third': typeof DashboardThirdRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/visit-log': typeof DashboardVisitLogRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/dashboard/about': typeof DashboardAboutLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/editor': typeof DashboardEditorLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/dashboard/articles'
    | '/dashboard/blog'
    | '/dashboard/categories'
    | '/dashboard/comments'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/personalInfo'
    | '/dashboard/tags'
    | '/dashboard/third'
    | '/dashboard/users'
    | '/dashboard/visit-log'
    | '/auth/login'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/editor'
    | '/dashboard/settings'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/dashboard/articles'
    | '/dashboard/blog'
    | '/dashboard/categories'
    | '/dashboard/comments'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/personalInfo'
    | '/dashboard/tags'
    | '/dashboard/third'
    | '/dashboard/users'
    | '/dashboard/visit-log'
    | '/auth/login'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/editor'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/dashboard/articles'
    | '/dashboard/blog'
    | '/dashboard/categories'
    | '/dashboard/comments'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/personalInfo'
    | '/dashboard/tags'
    | '/dashboard/third'
    | '/dashboard/users'
    | '/dashboard/visit-log'
    | '/auth/login'
    | '/dashboard/about'
    | '/dashboard/analytics'
    | '/dashboard/editor'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardBlogRoute: typeof DashboardBlogRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCommentsRoute: typeof DashboardCommentsRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardPersonalInfoRoute: typeof DashboardPersonalInfoRoute
  DashboardTagsRoute: typeof DashboardTagsRoute
  DashboardThirdRoute: typeof DashboardThirdRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVisitLogRoute: typeof DashboardVisitLogRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  DashboardAboutLazyRoute: typeof DashboardAboutLazyRoute
  DashboardAnalyticsLazyRoute: typeof DashboardAnalyticsLazyRoute
  DashboardEditorLazyRoute: typeof DashboardEditorLazyRoute
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardBlogRoute: DashboardBlogRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCommentsRoute: DashboardCommentsRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardPersonalInfoRoute: DashboardPersonalInfoRoute,
  DashboardTagsRoute: DashboardTagsRoute,
  DashboardThirdRoute: DashboardThirdRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVisitLogRoute: DashboardVisitLogRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  DashboardAboutLazyRoute: DashboardAboutLazyRoute,
  DashboardAnalyticsLazyRoute: DashboardAnalyticsLazyRoute,
  DashboardEditorLazyRoute: DashboardEditorLazyRoute,
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.lazy.tsx",
      "children": [
        "/",
        "/auth/forgot-password",
        "/dashboard/articles",
        "/dashboard/blog",
        "/dashboard/categories",
        "/dashboard/comments",
        "/dashboard/links",
        "/dashboard/media",
        "/dashboard/personalInfo",
        "/dashboard/tags",
        "/dashboard/third",
        "/dashboard/users",
        "/dashboard/visit-log",
        "/auth/login",
        "/dashboard/about",
        "/dashboard/analytics",
        "/dashboard/editor",
        "/dashboard/settings",
        "/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/dashboard/articles": {
      "filePath": "dashboard/articles.tsx"
    },
    "/dashboard/blog": {
      "filePath": "dashboard/blog.tsx"
    },
    "/dashboard/categories": {
      "filePath": "dashboard/categories.tsx"
    },
    "/dashboard/comments": {
      "filePath": "dashboard/comments.tsx"
    },
    "/dashboard/links": {
      "filePath": "dashboard/links.tsx"
    },
    "/dashboard/media": {
      "filePath": "dashboard/media.tsx"
    },
    "/dashboard/personalInfo": {
      "filePath": "dashboard/personalInfo.tsx"
    },
    "/dashboard/tags": {
      "filePath": "dashboard/tags.tsx"
    },
    "/dashboard/third": {
      "filePath": "dashboard/third.tsx"
    },
    "/dashboard/users": {
      "filePath": "dashboard/users.tsx"
    },
    "/dashboard/visit-log": {
      "filePath": "dashboard/visit-log.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx"
    },
    "/dashboard/about": {
      "filePath": "dashboard/about.lazy.tsx"
    },
    "/dashboard/analytics": {
      "filePath": "dashboard/analytics.lazy.tsx"
    },
    "/dashboard/editor": {
      "filePath": "dashboard/editor.lazy.tsx"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
